In [1]:
try:
  import numpy as np
  import pandas as pd
  from sklearn.model_selection import train_test_split
  from sklearn.preprocessing import StandardScaler
  from sklearn.svm import SVC
  from sklearn.pipeline import Pipeline
  from sklearn.model_selection import GridSearchCV
  from sklearn.metrics import accuracy_score

except ModuleNotFoundError as e:
  print(f"Module not found {e}\nCheck the spelling or use pip install")

In [2]:
df = pd.read_csv('/workspaces/machine-learning-workbench/Submarine_mine_detection_system/assets/training_sonar_data.csv', header=None)
df.head()

,0,1,2,3,4,5,6,7,8,9,...,51,52,53,54,55,56,57,58,59,60
0,0.0200,0.0371,0.0428,0.0207,0.0954,0.0986,0.1539,0.1601,0.3109,0.2111,...,0.0027,0.0065,0.0159,0.0072,0.0167,0.0180,0.0084,0.0090,0.0032,R
1,0.0453,0.0523,0.0843,0.0689,0.1183,0.2583,0.2156,0.3481,0.3337,0.2872,...,0.0084,0.0089,0.0048,0.0094,0.0191,0.0140,0.0049,0.0052,0.0044,R
2,0.0262,0.0582,0.1099,0.1083,0.0974,0.2280,0.2431,0.3771,0.5598,0.6194,...,0.0232,0.0166,0.0095,0.0180,0.0244,0.0316,0.0164,0.0095,0.0078,R
3,0.0100,0.0171,0.0623,0.0205,0.0205,0.0368,0.1098,0.1276,0.0598,0.1264,...,0.0121,0.0036,0.0150,0.0085,0.0073,0.0050,0.0044,0.0040,0.0117,R
4,0.0762,0.0666,0.0481,0.0394,0.0590,0.0649,0.1209,0.2467,0.3564,0.4459,...,0.0031,0.0054,0.0105,0.0110,0.0015,0.0072,0.0048,0.0107,0.0094,R

In [3]:
df[60].value_counts()

60
M    111
R     97
Name: count, dtype: int64

In [4]:
df.groupby(60).mean()

,0,1,2,3,4,5,6,7,8,9,...,50,51,52,53,54,55,56,57,58,59
60,,,,,,,,,,,,,,,,,,,,,
M,0.034989,0.045544,0.050720,0.064768,0.086715,0.111864,0.128359,0.149832,0.213492,0.251022,...,0.019352,0.016014,0.011643,0.012185,0.009923,0.008914,0.007825,0.009060,0.008695,0.006930
R,0.022498,0.030303,0.035951,0.041447,0.062028,0.096224,0.114180,0.117596,0.137392,0.159325,...,0.012311,0.010453,0.009640,0.009518,0.008567,0.007430,0.007814,0.006677,0.007078,0.006024

In [5]:
x = df.drop(columns=60)
y = df[60]

print(x.head())
print(y.head())

       0       1       2       3       4       5       6       7       8   \
0  0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109
1  0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337
2  0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598
3  0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598
4  0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564

       9   ...      50      51      52      53      54      55      56  \
0  0.2111  ...  0.0232  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180
1  0.2872  ...  0.0125  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140
2  0.6194  ...  0.0033  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316
3  0.1264  ...  0.0241  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050
4  0.4459  ...  0.0156  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072

       57      58      59
0  0.0084  0.0090  0.0032
1  0.0049  0.0052  0.0044
2  0.0164  0.0095  0.0078
3  0.0044  0.0040  0.0117
4  0.0048  0.0107  0.0094

[5 rows x 60 columns]
0    R
1    R
2    R
3    R
4    R
Name: 60, dtype: str

In [6]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2)
print(x.shape, X_train.shape, X_test.shape)
print(y.shape, y_train.shape, y_test.shape)

(208, 60) (166, 60) (42, 60)
(208,) (166,) (42,)

In [7]:
pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('svm', SVC())
])

In [8]:
param_grid = {
    'svm__kernel': ['rbf'],
    'svm__C': [0.1, 1, 10, 100],
    'svm__gamma': ['scale', 0.01, 0.001]
}

In [9]:
grid = GridSearchCV(pipeline, param_grid, cv=5)
grid.fit(X_train, y_train)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                       ('svm', SVC())]),
             param_grid={'svm__C': [0.1, 1, 10, 100],
                         'svm__gamma': ['scale', 0.01, 0.001],
                         'svm__kernel': ['rbf']})

In [10]:
print("Best:", grid.best_params_)
print("Accuracy:", grid.score(X_test, y_test))

Best: {'svm__C': 10, 'svm__gamma': 'scale', 'svm__kernel': 'rbf'}
Accuracy: 0.9047619047619048

In [11]:
import pickle

best_model = grid.best_estimator_

with open('sonar_model.pkl', 'wb') as f:
    pickle.dump(best_model, f)

In [12]:
a = np.asarray(df.iloc[2].drop(60))
a = a.reshape(1, -1)
a.shape

(1, 60)

In [14]:
prediction = best_model.predict(a)
print(a)

[[np.float64(0.0262) np.float64(0.0582) np.float64(0.1099)
  np.float64(0.1083) np.float64(0.0974) np.float64(0.228)
  np.float64(0.2431) np.float64(0.3771) np.float64(0.5598)
  np.float64(0.6194) np.float64(0.6333) np.float64(0.706)
  np.float64(0.5544) np.float64(0.532) np.float64(0.6479)
  np.float64(0.6931) np.float64(0.6759) np.float64(0.7551)
  np.float64(0.8929) np.float64(0.8619) np.float64(0.7974)
  np.float64(0.6737) np.float64(0.4293) np.float64(0.3648)
  np.float64(0.5331) np.float64(0.2413) np.float64(0.507)
  np.float64(0.8533) np.float64(0.6036) np.float64(0.8514)
  np.float64(0.8512) np.float64(0.5045) np.float64(0.1862)
  np.float64(0.2709) np.float64(0.4232) np.float64(0.3043)
  np.float64(0.6116) np.float64(0.6756) np.float64(0.5375)
  np.float64(0.4719) np.float64(0.4647) np.float64(0.2587)
  np.float64(0.2129) np.float64(0.2222) np.float64(0.2111)
  np.float64(0.0176) np.float64(0.1348) np.float64(0.0744)
  np.float64(0.013) np.float64(0.0106) np.float64(0.0033)
  np.float64(0.0232) np.float64(0.0166) np.float64(0.0095)
  np.float64(0.018) np.float64(0.0244) np.float64(0.0316)
  np.float64(0.0164) np.float64(0.0095) np.float64(0.0078)]]

In [15]:
from sklearn.metrics import classification_report

print(classification_report(y_train, prediction))

ValueError: Found input variables with inconsistent numbers of samples: [166, 1]